"""
rag_verifier.py - Stage 3B: RAG Grounding Verification
ControlPlane.ai (PS1 Architecture)

Features:
1. Enterprise RAG Retriever (RetEngine): Searches knowledge base for relevant policy documents.
2. Factual Grounding Verifier (RAGVerifier):
   - Numeric & Entity Verification: Validates exact numbers, currencies, and timeframes.
   - Claim Entailment Check: Computes Grounding Score G (0-10) and flags fabricated claims.
"""

import re
from typing import List, Tuple, Dict, Any, Set
from models import (
    Stage3BResult,
    KnowledgeChunk,
    ENTERPRISE_KNOWLEDGE_BASE
)


# Patterns to extract numbers, currency amounts, and timeframes
NUMERIC_ENTITY_PATTERN = re.compile(
    r"\$\s*[\d,]+(?:\.\d+)?|\b\d+(?:,\d+)*(?:\.\d+)?\s*(?:days?|business\s+days?|months?|years?|%|percent)\b|\b\d{2,}\b",
    re.IGNORECASE
)


# ============================================================================
# 1. Enterprise RAG Retriever (RetEngine)
# ============================================================================

def retrieve_knowledge_chunks(
    query_text: str,
    top_k: int = 2,
    kb: List[KnowledgeChunk] = ENTERPRISE_KNOWLEDGE_BASE
) -> List[KnowledgeChunk]:
    """
    Enterprise RAG Retriever (RetEngine)
    
    Scores knowledge base chunks against query/candidate keywords and content tokens.
    Returns the top-k most relevant source documents.
    """
    query_tokens = set(re.findall(r"\b\w+\b", query_text.lower()))
    
    scored_chunks: List[Tuple[float, KnowledgeChunk]] = []
    for chunk in kb:
        score = 0.0
        
        # 1. Keyword direct matching (High weight)
        for kw in chunk.keywords:
            if kw.lower() in query_text.lower():
                score += 3.0
                
        # 2. Content token overlap
        chunk_tokens = set(re.findall(r"\b\w+\b", chunk.content.lower()))
        overlap = query_tokens.intersection(chunk_tokens)
        score += len(overlap) * 0.5
        
        if score > 0:
            scored_chunks.append((score, chunk))
            
    # Sort descending by relevance score
    scored_chunks.sort(key=lambda x: x[0], reverse=True)
    return [chunk for _, chunk in scored_chunks[:top_k]]


# ============================================================================
# 2. Numeric & Claim Grounding Verifier (RAGVerifier)
# ============================================================================

def _extract_numeric_entities(text: str) -> List[str]:
    """Extracts all numbers, currency, and timeframe spans from text."""
    matches = NUMERIC_ENTITY_PATTERN.findall(text)
    return [re.sub(r"\s+", " ", m.strip()) for m in matches]


def _normalize_token(val: str) -> str:
    """Normalizes string for exact match (e.g. '$500' -> '$500', '30 days' -> '30 days')."""
    return re.sub(r"\s+", " ", val.strip().lower())


def verify_factual_grounding(
    candidate_response: str,
    query: str = "",
    kb: List[KnowledgeChunk] = ENTERPRISE_KNOWLEDGE_BASE
) -> Stage3BResult:
    """
    Stage 3B: RAG Grounding Verification
    
    1. Retrieves relevant enterprise source documents for the query/candidate.
    2. Verifies numeric facts (e.g. refund dollar caps, return windows, DTI thresholds).
    3. Computes Grounding Score G (0.0 to 10.0 scale, where 10 = fully grounded).
    
    Args:
        candidate_response: Draft response generated by Primary LLM.
        query: User input prompt or topic.
        kb: Knowledge base to verify against.
        
    Returns:
        Stage3BResult containing retrieved docs, grounding score, and mismatch flags.
    """
    # 1. Retrieve relevant source documents
    search_context = f"{query} {candidate_response}"
    retrieved_docs = retrieve_knowledge_chunks(search_context, top_k=2, kb=kb)

    # If no relevant enterprise policy applies (general greeting/chitchat), assume clean
    if not retrieved_docs:
        return Stage3BResult(
            retrieved_chunks=[],
            grounding_score=10.0,
            unsupported_claims=[],
            numeric_mismatches=[],
            rag_risk=0.0
        )

    # Aggregate combined source text for verification
    combined_source_text = " ".join(doc.content for doc in retrieved_docs)
    combined_source_lower = combined_source_text.lower()

    unsupported_claims: List[str] = []
    numeric_mismatches: List[str] = []
    penalty = 0.0

    # 2. Exact Numeric & Monetary Consistency Verification
    candidate_nums = _extract_numeric_entities(candidate_response)
    source_nums = [_normalize_token(s) for s in _extract_numeric_entities(combined_source_text)]
    source_num_set = set(source_nums)

    for raw_num in candidate_nums:
        norm_num = _normalize_token(raw_num)
        
        # Punctuation-safe word boundary check (comma/digit safe)
        pattern = r"(?<![\d,])" + re.escape(norm_num) + r"(?![\d,])"
        is_in_source = (norm_num in source_num_set) or bool(re.search(pattern, combined_source_lower))
        
        if not is_in_source:
            numeric_mismatches.append(f"Unverified numeric claim '{raw_num}' not found in source policy.")
            penalty += 3.5

    # 3. Sentence-Level Fact Consistency Check
    sentences = [s.strip() for s in re.split(r"[.!?]", candidate_response) if len(s.strip()) > 15]
    
    for sentence in sentences:
        s_tokens = set(re.findall(r"\b\w+\b", sentence.lower()))
        s_content = {t for t in s_tokens if len(t) > 3}
        
        if not s_content:
            continue

        source_tokens = set(re.findall(r"\b\w+\b", combined_source_lower))
        overlap_ratio = len(s_content.intersection(source_tokens)) / len(s_content)

        if overlap_ratio < 0.25:
            unsupported_claims.append(f"Ungrounded claim: '{sentence}'")
            penalty += 2.5

    # 4. Compute Grounding Score & Risk
    grounding_score = max(0.0, min(10.0, round(10.0 - penalty, 2)))
    rag_risk = round(10.0 - grounding_score, 2)

    return Stage3BResult(
        retrieved_chunks=retrieved_docs,
        grounding_score=grounding_score,
        unsupported_claims=unsupported_claims,
        numeric_mismatches=numeric_mismatches,
        rag_risk=rag_risk
    )
